# Generated by Django 4.1.2 on 2022-10-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_passwords_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwords",
            name="password",
            field=models.BinaryField(max_length=150),
        ),
    ]
