# Generated by Django 4.1.2 on 2022-10-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_passwords_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwords",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
