# Generated by Django 4.1.2 on 2022-10-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_passwords_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwords",
            name="custom_fields",
            field=models.TextField(null=True),
        ),
    ]
