# Generated by Django 4.1.2 on 2022-11-16 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_passwords_custom_fields_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwords",
            name="fields",
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("value", models.BinaryField(max_length=150)),
                (
                    "password",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="main.passwords",
                    ),
                ),
            ],
        ),
    ]
