# Generated by Django 4.1.2 on 2022-11-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_passwords_fields_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
